export const FLEET_MANAGER_EVENT_TYPES = Object.freeze({
  workorder_created: "workorder.created",
  workorder_updated: "workorder.updated",
  workorder_assigned: "workorder.assigned",
  workorder_started: "workorder.started",
  workorder_waiting_parts: "workorder.waiting_parts",
  workorder_on_hold: "workorder.on_hold",
  workorder_completed: "workorder.completed",
  workorder_closed: "workorder.closed",
  workorder_escalated: "workorder.escalated",
  predictive_generated: "aimi.predictive.generated",
  predictive_updated: "aimi.predictive.updated",
  predictive_escalated: "aimi.predictive.escalated",
  insight_generated: "aimi.insight.generated",
  insight_updated: "aimi.insight.updated",
  insight_approved: "aimi.insight.approved",
  insight_applied: "aimi.insight.applied",
  pm_compliance_failed: "pm.compliance.failed",
  pm_compliance_passed: "pm.compliance.passed",
  inventory_request_submitted: "inventory.request.submitted",
  routing_assigned: "routing.assigned",
  scheduling_created: "scheduling.created",
  notification_generated: "notification.generated",
});

export const FLEET_MANAGER_INSIGHT_TYPES: readonly string[] = Object.freeze([
  FLEET_MANAGER_EVENT_TYPES.predictive_generated,
  FLEET_MANAGER_EVENT_TYPES.predictive_updated,
  FLEET_MANAGER_EVENT_TYPES.predictive_escalated,
  FLEET_MANAGER_EVENT_TYPES.insight_generated,
  FLEET_MANAGER_EVENT_TYPES.insight_updated,
  FLEET_MANAGER_EVENT_TYPES.insight_approved,
  FLEET_MANAGER_EVENT_TYPES.insight_applied,
]);
