export { canAccessFleetManagerDashboard, canMutateFleetManagerDashboard, fleetManagerTenantAllowed } from "./fleet-manager-dashboard.rbac";
export { FLEET_MANAGER_EVENT_TYPES } from "./fleet-manager-dashboard.events";
export { fleetManagerRequest, FLEET_MANAGER_CLIENT_ROUTES } from "./api/fleet-manager-dashboard.api.client";
export { listFleetAssets } from "./api/assets.api.client";
export { listFleetWorkorders } from "./api/workorders.api.client";
export { listFleetPmSchedules } from "./api/pm.api.client";
export { listFleetInventory } from "./api/inventory.api.client";
export { listFleetTelematics } from "./api/telematics.api.client";
export { listFleetAimiInsights } from "./api/aimi-insights.api.client";
export { loadFleetManagerSession, useFleetManagerApi } from "./hooks/useFleetManagerApi";
export { default as FleetManagerDashboardPage } from "./page";
export { default as FleetManagerDashboardLayout } from "./layout";
