export const MASTER_TECH_EVENT_TYPES = Object.freeze({
  workorder_created: "workorder.created",
  workorder_updated: "workorder.updated",
  workorder_assigned: "workorder.assigned",
  workorder_started: "workorder.started",
  workorder_waiting_parts: "workorder.waiting_parts",
  workorder_on_hold: "workorder.on_hold",
  workorder_completed: "workorder.completed",
  workorder_closed: "workorder.closed",
  workorder_escalated: "workorder.escalated",
  predictive_generated: "aimi.predictive.generated",
  predictive_updated: "aimi.predictive.updated",
  predictive_escalated: "aimi.predictive.escalated",
  learning_generated: "aimi.learning.insight.generated",
  learning_approved: "aimi.learning.insight.approved",
  learning_applied: "aimi.learning.insight.applied",
  insight_generated: "aimi.insight.generated",
  insight_updated: "aimi.insight.updated",
  insight_approved: "aimi.insight.approved",
  insight_applied: "aimi.insight.applied",
  diagnostic_started: "diagnostic.step.started",
  diagnostic_completed: "diagnostic.step.completed",
  diagnostic_skipped: "diagnostic.step.skipped",
  diagnostic_verified: "diagnostic.verification.completed",
  pm_started: "pm.started",
  pm_finding_logged: "pm.finding.logged",
  pm_completed: "pm.completed",
  pm_compliance_failed: "pm.compliance.failed",
  pm_compliance_passed: "pm.compliance.passed",
  routing_assigned: "routing.assigned",
  routing_updated: "routing.updated",
  routing_conflict: "routing.conflict",
  routing_overridden: "routing.overridden",
  scheduling_created: "scheduling.created",
  scheduling_updated: "scheduling.updated",
  scheduling_escalated: "scheduling.escalated",
  scheduling_conflict: "scheduling.conflict",
  scheduling_canceled: "scheduling.canceled",
  voice_received: "voice.command.received",
  voice_processed: "voice.command.processed",
  voice_failed: "voice.command.failed",
  voice_translated: "voice.command.translated",
  voice_logged: "voice.command.logged",
  notification_generated: "notification.generated",
});

export const MASTER_TECH_EVENT_FEED_TYPES: readonly string[] = Object.freeze([
  MASTER_TECH_EVENT_TYPES.workorder_created,
  MASTER_TECH_EVENT_TYPES.workorder_updated,
  MASTER_TECH_EVENT_TYPES.workorder_assigned,
  MASTER_TECH_EVENT_TYPES.workorder_started,
  MASTER_TECH_EVENT_TYPES.workorder_waiting_parts,
  MASTER_TECH_EVENT_TYPES.workorder_on_hold,
  MASTER_TECH_EVENT_TYPES.workorder_completed,
  MASTER_TECH_EVENT_TYPES.workorder_closed,
  MASTER_TECH_EVENT_TYPES.workorder_escalated,
  MASTER_TECH_EVENT_TYPES.predictive_generated,
  MASTER_TECH_EVENT_TYPES.predictive_updated,
  MASTER_TECH_EVENT_TYPES.predictive_escalated,
  MASTER_TECH_EVENT_TYPES.learning_generated,
  MASTER_TECH_EVENT_TYPES.learning_approved,
  MASTER_TECH_EVENT_TYPES.learning_applied,
  MASTER_TECH_EVENT_TYPES.insight_generated,
  MASTER_TECH_EVENT_TYPES.insight_updated,
  MASTER_TECH_EVENT_TYPES.insight_approved,
  MASTER_TECH_EVENT_TYPES.insight_applied,
  MASTER_TECH_EVENT_TYPES.diagnostic_started,
  MASTER_TECH_EVENT_TYPES.diagnostic_completed,
  MASTER_TECH_EVENT_TYPES.diagnostic_skipped,
  MASTER_TECH_EVENT_TYPES.diagnostic_verified,
  MASTER_TECH_EVENT_TYPES.pm_started,
  MASTER_TECH_EVENT_TYPES.pm_finding_logged,
  MASTER_TECH_EVENT_TYPES.pm_completed,
  MASTER_TECH_EVENT_TYPES.pm_compliance_failed,
  MASTER_TECH_EVENT_TYPES.pm_compliance_passed,
  MASTER_TECH_EVENT_TYPES.routing_assigned,
  MASTER_TECH_EVENT_TYPES.routing_updated,
  MASTER_TECH_EVENT_TYPES.routing_conflict,
  MASTER_TECH_EVENT_TYPES.routing_overridden,
  MASTER_TECH_EVENT_TYPES.scheduling_created,
  MASTER_TECH_EVENT_TYPES.scheduling_updated,
  MASTER_TECH_EVENT_TYPES.scheduling_escalated,
  MASTER_TECH_EVENT_TYPES.scheduling_conflict,
  MASTER_TECH_EVENT_TYPES.scheduling_canceled,
  MASTER_TECH_EVENT_TYPES.voice_received,
  MASTER_TECH_EVENT_TYPES.voice_processed,
  MASTER_TECH_EVENT_TYPES.voice_failed,
  MASTER_TECH_EVENT_TYPES.voice_translated,
  MASTER_TECH_EVENT_TYPES.voice_logged,
  MASTER_TECH_EVENT_TYPES.notification_generated,
]);

export function isMasterTechEventType(event_type: string): boolean {
  let index = 0;
  while (index < MASTER_TECH_EVENT_FEED_TYPES.length) {
    if (MASTER_TECH_EVENT_FEED_TYPES[index] === event_type) {
      return true;
    }
    index = index + 1;
  }
  return false;
}
