export const GLOBAL_DASHBOARD_INTEGRATION_EVENT_TYPES = Object.freeze({
  workorder_created: "workorder.created",
  workorder_updated: "workorder.updated",
  workorder_assigned: "workorder.assigned",
  workorder_started: "workorder.started",
  workorder_waiting_parts: "workorder.waiting_parts",
  workorder_on_hold: "workorder.on_hold",
  workorder_completed: "workorder.completed",
  workorder_closed: "workorder.closed",
  workorder_escalated: "workorder.escalated",
  pm_started: "pm.started",
  pm_finding_logged: "pm.finding.logged",
  pm_completed: "pm.completed",
  pm_compliance_failed: "pm.compliance.failed",
  pm_compliance_passed: "pm.compliance.passed",
  predictive_generated: "aimi.predictive.generated",
  predictive_updated: "aimi.predictive.updated",
  predictive_escalated: "aimi.predictive.escalated",
  insight_generated: "aimi.insight.generated",
  insight_updated: "aimi.insight.updated",
  insight_approved: "aimi.insight.approved",
  insight_applied: "aimi.insight.applied",
  bulk_import_completed: "bulk_import.completed",
  configuration_pack_applied: "configuration_pack.applied",
});

export const GLOBAL_DASHBOARD_INTEGRATION_AIMI_TYPES: readonly string[] = Object.freeze([
  GLOBAL_DASHBOARD_INTEGRATION_EVENT_TYPES.predictive_generated,
  GLOBAL_DASHBOARD_INTEGRATION_EVENT_TYPES.predictive_updated,
  GLOBAL_DASHBOARD_INTEGRATION_EVENT_TYPES.predictive_escalated,
  GLOBAL_DASHBOARD_INTEGRATION_EVENT_TYPES.insight_generated,
  GLOBAL_DASHBOARD_INTEGRATION_EVENT_TYPES.insight_updated,
  GLOBAL_DASHBOARD_INTEGRATION_EVENT_TYPES.insight_approved,
  GLOBAL_DASHBOARD_INTEGRATION_EVENT_TYPES.insight_applied,
]);
